// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXPK-6QgiS1TpPmjXVo3mVL8FDz2GWN1c',
    appId: '1:576396770346:web:1a4daeec37f6f982f29753',
    messagingSenderId: '576396770346',
    projectId: 'calori-tracker-c2f3e',
    authDomain: 'calori-tracker-c2f3e.firebaseapp.com',
    storageBucket: 'calori-tracker-c2f3e.appspot.com',
    measurementId: 'G-2LPM8RTBZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxU9bswxembHKsBT1tbli_v91sEakA0V0',
    appId: '1:576396770346:android:a339f1498ae8235bf29753',
    messagingSenderId: '576396770346',
    projectId: 'calori-tracker-c2f3e',
    storageBucket: 'calori-tracker-c2f3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJHaglzw_VV9sBYmxBdhfH3FHptBJer3k',
    appId: '1:576396770346:ios:9dc763ec16ff8751f29753',
    messagingSenderId: '576396770346',
    projectId: 'calori-tracker-c2f3e',
    storageBucket: 'calori-tracker-c2f3e.appspot.com',
    iosClientId: '576396770346-2isv1ek16t6ncfnhr8dotgqn8nrcarn2.apps.googleusercontent.com',
    iosBundleId: 'com.example.caloriTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJHaglzw_VV9sBYmxBdhfH3FHptBJer3k',
    appId: '1:576396770346:ios:9dc763ec16ff8751f29753',
    messagingSenderId: '576396770346',
    projectId: 'calori-tracker-c2f3e',
    storageBucket: 'calori-tracker-c2f3e.appspot.com',
    iosClientId: '576396770346-2isv1ek16t6ncfnhr8dotgqn8nrcarn2.apps.googleusercontent.com',
    iosBundleId: 'com.example.caloriTracker',
  );
}
